export const CHANGE_NAME = 'CHANGE__NAME';
export const SELECT_MASTER_GROUP = 'SELECT_MASTER_GROUP';
export const NEXT_STEP = 'NEXT_STEP';
export const PREV_STEP = 'PREV_STEP';

export const SET_INITIAL_DATE = 'SET_INITIAL_DATE';
export const SET_SELECTED_DATE_TIME_LIST = 'SET_SELECTED_DATE_TIME_LIST';
export const SELECT_TIME = 'SELECT_TIME';
export const SET_DATE_TIME_STRING = 'SET_DATE_TIME_STRING';
